version: '3.8'

services:
    backend:
        image: spitii/devops-backend:2.0
        networks:
            - my-network
            - database
        depends_on:
            - database
            - httpd

    database:
        image: spitii/devops-database:1.0
        volumes:
            - TP1DB:/var/lib/postgresql/data
        networks:
            - database

    httpd:
        build: ./httpd
        ports:
            - "80:80"
        networks:
            - my-network

    frontend:
        build: ./frontend
        networks:
            - my-network
        ports:
            - "8080:80"
        depends_on:
            - httpd

networks:
    my-network:
    database:
        
volumes:
  TP1DB:
    