version: '3.8'

services:
    backend:
        image: spitii/devops-backend:2.0
        networks:
            - my-network
            - database
        depends_on:
            - database

    database:
        image: spitii/devops-database:1.0
        volumes:
            - TP1DB:/var/lib/postgresql/data
        networks:
            - database

    httpd:
        build: ./httpd
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - backend
        environment:
            - URL="https://localhost:443"

networks:
    my-network:
    database:
        
volumes:
  TP1DB:
    