- name: Deploy FrontEnd
  docker_container:
    name: frontend
    image: spitii/devops-frontend:master
    recreate: true
    pull: true
    networks:
      - name: Front-end
    env:
      VUE_APP_API_URL: "http://matthieu.lapetitte.takima.cloud:80/api"
