- name: Deploy Backend
  docker_container:
    name: backend
    image: spitii/devops-backend:master
    recreate: true
    pull: true
    networks:
      - name: DataBase
      - name: Back-end
    env:
      DB_URL: "database"
      DB_NAME: "db"
      DB_USER: "usr"
      DB_PASS: "pwd"