- name: Deploy Proxy
  docker_container:
    name: httpd
    image: spitii/devops-httpd:master
    recreate: true
    pull: true
    networks:
      - name: Back-end
      - name: Front-end
    ports:
      - "80:80"
    env:
      URL: "http://matthieu.lapetitte.takima.cloud:80"
      FRONTEND_NAME: "frontend"
      BACKEND_NAME: "backend"